"""create_city_log_model

Revision ID: 79a825510413
Revises: 82d94d242a0c
Create Date: 2023-11-15 01:52:31.578710

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "79a825510413"
down_revision: Union[str, None] = "82d94d242a0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "city_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.Enum("CREATED", "UPDATED", "DELETED", "SELECTED", name="citylogstatus"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["city.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_city_log_id"), "city_log", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_city_log_id"), table_name="city_log")
    op.drop_table("city_log")
    # ### end Alembic commands ###
